# Generated by Django 4.2.10 on 2024-03-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('partners', models.CharField(choices=[('HT:BLS', 'Health Training: Basic Life Support'), ('HT:BAP', 'Health Training: Breast Advocacy and PFA'), ('HT:FAST', 'Health Training: FAST'), ('HE:OH', 'Health Education: Oral Health'), ('HE:MHPS', 'Health Education: MHPS'), ('DPT', 'Disaster Preparedness Training'), ('DPL', 'Disaster Preparedness Lecture')], max_length=8)),
                ('stakeholder_category', models.CharField(choices=[('P', 'Private'), ('G', 'Government')], max_length=64)),
            ],
        ),
    ]
