# Generated by Django 4.2.11 on 2024-03-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scope_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='type_of_partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_partnership', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=64)),
                ('partnership_extension', models.CharField(choices=[('', 'Select Partnership Extension'), ('HT:BLS', 'Health Training: Basic Life Support'), ('HT:BAP', 'Health Training: Breast Advocacy and PFA'), ('HT:FAST', 'Health Training: FAST'), ('HE:OH', 'Health Education: Oral Health'), ('HE:MHPS', 'Health Education: MHPS'), ('DPT', 'Disaster Preparedness Training'), ('DPL', 'Disaster Preparedness Lecture')], max_length=8)),
                ('stakeholder_category', models.CharField(choices=[('', 'Select Stakeholder Category'), ('P', 'Private'), ('G', 'Government')], max_length=64, null=True)),
                ('second_category', models.CharField(choices=[('', 'Select Second Stakeholder Category'), ('1', 'NGO'), ('1', 'Company'), ('1', 'Educational Institution'), ('1', 'Others'), ('2', 'LGU'), ('2', 'National Government Agency'), ('2', 'Educational Institution'), ('2', 'Others')], max_length=64, null=True)),
                ('other_choice', models.CharField(blank=True, max_length=64)),
                ('Agreement_Start_Date', models.DateField()),
                ('Agreement_End_Date', models.DateField()),
                ('files', models.FileField(upload_to='partner_requirements/')),
                ('type_of_partnership', models.ManyToManyField(blank=True, to='partners_forms.type_of_partnership')),
            ],
        ),
    ]
