# Generated by Django 4.2.11 on 2024-04-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files_obj',
            name='Partner',
        ),
        migrations.AddField(
            model_name='files_obj',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='partners_forms.partner'),
        ),
    ]
