# Generated by Django 4.2.10 on 2024-04-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files_obj',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='Type_obj',
            new_name='Type',
        ),
    ]
