# Generated by Django 4.2.11 on 2024-03-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partnership_extension',
            field=models.CharField(choices=[('', 'Select Partnership Extension'), ('HT:BLS', 'Health Training: Basic Life Support'), ('HT:BAP', 'Health Training: Breast Advocacy and PFA'), ('HT:FAST', 'Health Training: FAST'), ('HE:OH', 'Health Education: Oral Health'), ('HE:MHPS', 'Health Education: MHPS'), ('DPT', 'Disaster Preparedness Training'), ('DPL', 'Disaster Preparedness Lecture')], max_length=8),
        ),
    ]
