# Generated by Django 4.2.11 on 2024-03-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0002_alter_partner_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='files',
            field=models.FileField(upload_to='partner_requirements/'),
        ),
    ]
