# Generated by Django 4.2.11 on 2024-03-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0002_alter_partner_partnership_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='second_category',
            field=models.CharField(choices=[('', 'Select Second Stakeholder Category'), ('1', 'NGO'), ('1', 'Company'), ('1', 'Educational Institution'), ('1', 'Others'), ('2', 'LGU'), ('2', 'National Government Agency'), ('2', 'Educational Institution'), ('2', 'Others')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='stakeholder_category',
            field=models.CharField(choices=[('', 'Select Stakeholder Category'), ('P', 'Private'), ('G', 'Government')], max_length=64, null=True),
        ),
    ]
