# Generated by Django 4.2.11 on 2024-03-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0004_remove_partner_stakeholder_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='stakeholder_category',
            field=models.CharField(choices=[('', 'Select Stakeholder Category'), ('P', 'Private'), ('G', 'Government')], max_length=64, null=True),
        ),
    ]
