# Generated by Django 4.2.10 on 2024-03-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0004_rename_name_partner_partner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='type_of_partnership',
            field=models.CharField(choices=[('O', 'Others'), ('PT1', 'Partner Type 1'), ('PT2', 'Partner Type 2')], default='Type of Partnership', max_length=64),
        ),
    ]
