# Generated by Django 4.2.10 on 2024-03-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0005_partner_type_of_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='type_of_partnership',
            field=models.CharField(choices=[('O', 'Others'), ('PT1', 'Partner Type 1'), ('PT2', 'Partner Type 2')], default=False, max_length=64),
        ),
    ]
