# Generated by Django 4.2.11 on 2024-03-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0005_partner_stakeholder_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partnership_extension',
            field=models.CharField(choices=[('', 'Select Partnership Extension'), ('Health Training: Basic Life Support', 'Health Training: Basic Life Support'), ('Health Training: Breast Advocacy and PFA', 'Health Training: Breast Advocacy and PFA'), ('Health Training: FAST', 'Health Training: FAST'), ('Health Education: Oral Health', 'Health Education: Oral Health'), ('Health Education: MHPS', 'Health Education: MHPS'), ('Disaster Preparedness Training', 'Disaster Preparedness Training'), ('Disaster Preparedness Lecture', 'Disaster Preparedness Lecture')], max_length=64),
        ),
        migrations.AlterField(
            model_name='partner',
            name='stakeholder_category',
            field=models.CharField(choices=[('', 'Select Stakeholder Category'), ('Private', 'Private'), ('Government', 'Government')], max_length=64, null=True),
        ),
    ]
