# Generated by Django 4.2.10 on 2024-03-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0006_alter_partner_type_of_partnership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partners',
            new_name='partnership_extension',
        ),
    ]
