# Generated by Django 4.2.10 on 2024-03-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0007_rename_partners_partner_partnership_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='other_choice',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
