# Generated by Django 4.2.10 on 2024-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0010_alter_partner_second_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='other_choice',
            field=models.CharField(default='N/a', max_length=64),
        ),
    ]
