# Generated by Django 4.2.10 on 2024-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0011_alter_partner_other_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='other_choice',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
