# Generated by Django 4.2.10 on 2024-03-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0012_alter_partner_other_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='type_of_partnership',
            field=models.CharField(blank=True, choices=[('O', 'Others'), ('PT1', 'Partner Type 1'), ('PT2', 'Partner Type 2')], max_length=4),
        ),
        migrations.AddField(
            model_name='partner',
            name='scope_of_work',
            field=models.ManyToManyField(blank=True, to='partners_forms.scope_of_work'),
        ),
    ]
