# Generated by Django 4.2.10 on 2024-03-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0013_scope_of_work_alter_partner_type_of_partnership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='scope_of_work',
            field=models.ManyToManyField(blank=True, null=True, to='partners_forms.scope_of_work'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type_of_partnership',
            field=models.CharField(blank=True, choices=[('O', 'Others'), ('PT1', 'Partner Type 1'), ('PT2', 'Partner Type 2')], max_length=4, null=True),
        ),
    ]
