# Generated by Django 4.2.10 on 2024-03-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0015_alter_partner_scope_of_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='scope_of_work',
        ),
        migrations.DeleteModel(
            name='Scope_of_work',
        ),
    ]
