# Generated by Django 4.2.10 on 2024-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0016_remove_partner_scope_of_work_delete_scope_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='scope_of_work',
            field=models.ManyToManyField(blank=True, null=True, to='partners_forms.scope_of_work'),
        ),
    ]
