# Generated by Django 5.0.3 on 2024-03-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0018_alter_partner_scope_of_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='scope_of_work',
        ),
    ]
