# Generated by Django 5.0.3 on 2024-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners_forms', '0019_remove_partner_scope_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_of_partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_partnership', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='partner',
            name='type_of_partnership',
        ),
        migrations.AddField(
            model_name='partner',
            name='type_of_partnership',
            field=models.ManyToManyField(blank=True, null=True, to='partners_forms.type_of_partnership'),
        ),
    ]
