# Generated by Django 4.2.10 on 2024-04-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='img',
        ),
        migrations.AddField(
            model_name='program',
            name='program_img',
            field=models.ImageField(blank=True, upload_to='volunteer_forms/static/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
