# Generated by Django 4.2.10 on 2024-04-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_img',
            field=models.ImageField(blank=True, upload_to='volunteer_forms/static/'),
        ),
    ]
