# Generated by Django 4.2.10 on 2024-03-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='otherOccu',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
