# Generated by Django 4.2.10 on 2024-04-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_forms', '0002_rename_contact_volunteer_contactnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_img',
            field=models.ImageField(blank=True, upload_to='static/volunteer_forms/media'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='officeAdd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='religion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='workSched',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
