# Generated by Django 4.2.10 on 2024-03-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_forms', '0002_volunteer_otheroccu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='volunteer_forms.insurance'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license', to='volunteer_forms.license'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='volunteer_forms.student'),
        ),
    ]
