# Generated by Django 4.2.10 on 2024-04-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_forms', '0003_alter_program_description_alter_program_program_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_img',
            field=models.ImageField(blank=True, upload_to='volunteer_forms/static/volunteer_forms/media'),
        ),
    ]
