# Generated by Django 4.2.10 on 2024-03-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_forms', '0003_alter_volunteer_insurance_alter_volunteer_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='occupation',
            field=models.CharField(choices=[('Physician', 'Physician'), ('Nurse', 'Nurse'), ('Pharmacist', 'Pharmacist'), ('Dentist', 'Dentist'), ('ENT', 'ENT'), ('Teacher', 'Teacher'), ('Other', 'Other')], max_length=50),
        ),
    ]
