# Generated by Django 4.2.10 on 2024-04-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_forms', '0004_alter_program_program_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
